spring.application.name=diagnosticar-api

# Conexão com o TiDB Cloud (MySQL na Nuvem)
spring.datasource.url=jdbc:mysql://gateway01.us-east-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY&useSSL=true&serverTimezone=UTC
spring.datasource.username=3o1SSQy235TsBBb.root
spring.datasource.password=O1rlVKgThGQ0otR1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

openai.api.key=${OPENAI_API_KEY:chave_temporaria}